---
title: "Docker_permission_denied"
author: "Thomas Rauter"
date: "10 June, 2024"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Docker-permission-denied}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

If you face 'permission denied' issues, you might need to add your user to the Docker group. Follow these steps:

**1.  Create the Docker Group (if it doesn't already exist):**

``` sh
sudo groupadd docker
```

This command creates a Docker group if it does not already exist on your system.

**2.  Add Your User to the Docker Group:**

``` sh
sudo usermod -aG docker $USER
```

This command adds your user to the Docker group, which allows you to run Docker commands without sudo.

**3.  Log Out and Log Back In:**

This step is necessary to apply the group membership changes. After logging back in, you should be able to run Docker commands without sudo.

Alternatively, you can use the following command to apply the group changes immediately without logging out and back in:

``` sh
newgrp docker
```

**4.  Verify Docker Permissions:**

To check if the permission issue is resolved, run a simple Docker command:

``` sh
docker run hello-world
```

If the command runs successfully, you have configured Docker correctly.

**5.  Ensure Docker Service is Running:**

If you still encounter issues, ensure that the Docker service is running:

``` sh
sudo systemctl start docker
sudo systemctl enable docker
```

Following these steps will help you resolve permission issues and enable you to pull and run the Docker container without using `sudo`.
