# Exported function: cluster_hits() --------------------------------------------

#' Cluster Hits from Top Tables
#'
#' Performs clustering on hits from top tables generated by differential 
#' expression analysis.
#' This function filters hits based on adjusted p-value thresholds, extracts 
#' spline coefficients for 
#' significant features, normalizes these coefficients, and applies hierarchical 
#' clustering. The results,
#' including clustering assignments and normalized spline curves, are saved in a 
#' specified directory and
#' compiled into an HTML report.
#'
#' @param top_tables A list of data frames, each representing a top table from 
#' differential expression
#'        analysis, containing at least 'adj.P.Val' and expression data columns.
#' @param data The original expression dataset used for differential expression 
#' analysis.
#' @param meta Metadata dataframe corresponding to the `data`, must include a 
#' 'Time' column and any columns
#'        specified by `conditions`.
#' @param conditions Character vector specifying the column names in `meta` used 
#' to define groups for
#'        analysis.
#' @param p_values Numeric vector of p-value thresholds for filtering hits in 
#' each top table.
#' @param clusters Integer vector specifying the number of clusters to cut the 
#' dendrogram into, for each
#'        group factor.
#' @param report_dir Character string specifying the directory path where the 
#' HTML report and any
#'        other output files should be saved.
#'
#' @return A list where each element corresponds to a group factor and contains 
#' the clustering results,
#'         including `clustered_hits` data frame, hierarchical clustering object 
#'         `hc`, `curve_values`
#'         data frame with normalized spline curves, and `top_table` with 
#'         cluster assignments.
#'
#' @examples
#' \dontrun{
#'   cluster_results <- cluster_hits(top_tables, data, meta, c("GroupFactor"), 
#'                                   c(0.05),
#'                                   c(3), "path/to/report/dir")
#' }
#'
#' 
#' @seealso \code{\link[limma]{topTable}}, \code{\link[stats]{hclust}}
#' 
#' @export
#' 
cluster_hits <- function(top_tables, 
                         data, 
                         meta, 
                         spline_params,
                         condition, 
                         p_values, 
                         clusters, 
                         report_dir) {
  
  control_inputs_cluster_hits(top_tables = top_tables, 
                              data = data, 
                              meta = meta, 
                              spline_params = spline_params,
                              condition = condition, 
                              p_values = p_values, 
                              clusters = clusters, 
                              report_dir = report_dir)
  
  all_levels_clustering <- perform_clustering(top_tables = top_tables,
                                              p_values = p_values,
                                              clusters = clusters,
                                              meta = meta,
                                              condition = condition)
  
  make_clustering_report(all_levels_clustering = all_levels_clustering, 
                         condition = condition, 
                         data = data, 
                         meta = meta, 
                         p_values = p_values, 
                         report_dir = report_dir,
                         feature_names = feature_names)
  
  return(all_levels_clustering)
}



# Level 1 internal functions ---------------------------------------------------


control_inputs_cluster_hits <- function(top_tables, 
                                        data, 
                                        meta, 
                                        spline_params,
                                        condition, 
                                        p_values, 
                                        clusters, 
                                        report_dir) {
  if (!is.list(top_tables) || !all(sapply(top_tables, is.data.frame))) {
    stop("top_tables must be a list of dataframes")
  }
  
  if (!is.matrix(data)) {
    stop("data must be a matrix")
  }
  
  if (!is.data.frame(meta) || !"Time" %in% names(meta)) {
    stop("meta must be a dataframe")
  }
  
  
  if ("spline_type" %in% names(spline_params)) {
    if (!all(spline_params$spline_type %in% c("b", "n"))) {
      stop("Elements of spline_type must be either 'b' for B-splines or 'n'. for
           natural cubic splines")
    }
  } else {
    stop("spline_type is missing.")
  }
  
  # Check if degrees exists and is an integer vector
  if ("degrees" %in% names(spline_params)) {
    if (!all(spline_params$degrees == as.integer(spline_params$degrees))) {
      stop("degrees must be an integer vector.")
    }
  } else if (!all(spline_params$spline_type %in% c("n"))) {
    stop("degrees is missing.")
  }
  
  # Check if DoFs exists and is an integer vector
  if ("DoFs" %in% names(spline_params)) {
    if (!all(spline_params$DoFs == as.integer(spline_params$DoFs))) {
      stop("DoFs must be an integer vector.")
    }
  }
  
  # Check if knots exists and is a list of numeric vectors
  if ("knots" %in% names(spline_params)) {
    if (!is.list(spline_params$knots) || 
        any(sapply(spline_params$knots, function(x) !is.numeric(x)))) {
      stop("knots must be a list of numeric vectors.")
    }
  }
  
  if (("DoFs" %in% names(spline_params)) && 
      ("knots" %in% names(spline_params))) {
    stop("Either DoFs or knots must be present, but not both.")
  } else if (!("DoFs" %in% names(spline_params)) && 
             !("knots" %in% names(spline_params))) {
    stop("At least one of DoFs or knots must be present.")
  }
  
  # Check if bknots exists and is a list of numeric vectors
  if ("bknots" %in% names(spline_params)) {
    if (!is.list(spline_params$bknots) || 
        any(sapply(spline_params$bknots, function(x) !is.numeric(x)))) {
      stop("bknots must be a list of numeric vectors.")
    }
  }
  
  
  if (!(is.character(condition)) || length(condition) != 1) {
    stop("condition must be a character vector with length 1")
  }
  
  if (!is.numeric(p_values)) {
    stop("p_values must be a numeric vector")
  }
  
  if (!is.list(clusters) || 
      !all(sapply(clusters, function(x) is.character(x) || is.numeric(x)))) {
    stop("clusters must be a list containing only character or numeric types.")
  }
  
  if (!is.character(report_dir) || length(report_dir) != 1) {
    stop("report_dir must be a character vector with length 1")
  }
}


perform_clustering <- function(top_tables,
                               p_values,
                               clusters,
                               meta,
                               condition) {
  levels <- unique(meta[[condition]])
  
  all_levels_clustering <- mapply(process_level_cluster, 
                                  top_tables, 
                                  p_values, 
                                  clusters, 
                                  levels, 
                                  MoreArgs = list(meta = meta, 
                                                  condition = condition),
                                  SIMPLIFY = FALSE)  # Return a list
}



#' @importFrom dplyr filter
#'
make_clustering_report <- function(all_levels_clustering, 
                                   condition, 
                                   data, 
                                   meta, 
                                   p_values, 
                                   report_dir,
                                   feature_names) {
  
  # To extract the stored value for the potential auto cluster decision.
  clusters <- c()
  for (i in seq_along(all_levels_clustering)) {
    clusters <- c(clusters, as.integer(all_levels_clustering[[i]]$clusters))
    all_levels_clustering[[i]]$clusters <- NULL
  }
  
  if (!dir.exists(report_dir)) {
    dir.create(report_dir)
  }
  
  plot_list <- list()
  plot_list_nrows <- list()
  
  i <- 0
  for (level_clustering in all_levels_clustering) {
    i <- i + 1
    
    curve_values <- level_clustering$curve_values
    
    # debug(plot_heatmap)
    # heatmap <- plot_heatmap(data,
    #                         meta,
    #                         condition,
    #                         feature_names,
    #                         level_clustering$clustered_hits)
    
    title <- 
      "Exponential phase\n\nHierarchical Clustering Dendrogram 
       (colors = clusters)"
    dendrogram <- plot_dendrogram(level_clustering$hc, clusters[i], title)
    
    title <- 
      "Average Curves by Cluster (colors not matching with plot above!)"
    p_curves <- plot_all_shapes(curve_values, title)
    
    title <- paste("min-max normalized shapes | ", "cluster", sep = " ")
    consensus_shape_plots <- plot_consensus_shapes(curve_values, title)
    
    main_title <- paste(",cluster:", 1, sep = " ")
    
    top_table <- level_clustering$top_table
    p_value <- p_values[i]
    levels <- as.character(unique(meta[[condition]]))
    meta_level <- meta %>% dplyr::filter(.data[[condition]] == levels[i])
    sample_names <- as.character(meta_level$Sample)
    data_level <- data[, colnames(data) %in% sample_names]
    
    composite_plots <- list()
    nrows <- list()
    
    for (nr_cluster in unique(na.omit(top_table$cluster))) {
      main_title <- paste(",cluster:", nr_cluster, sep = " ")
      
      top_table_filt <- top_table %>%
        dplyr::filter(adj.P.Val < p_value, .data$cluster == nr_cluster)
      
      plot_splines_result <- plot_splines(top_table_filt, 
                                          data_level, 
                                          meta_level, 
                                          main_title)
      
      composite_plots[[length(composite_plots) + 1]] <- 
        plot_splines_result$composite_plot 
      
      nrows[[length(nrows) + 1]] <- plot_splines_result$nrows 
    }
    
    plot_list <- c(plot_list, list(dendrogram, p_curves), 
                   consensus_shape_plots, composite_plots)
    
    plot_list_nrows <- c(plot_list_nrows, 2, 2, 
                         rep(1, length(consensus_shape_plots)), unlist(nrows))
    
  }
  
  generate_report_html(plot_list, 
                       plot_list_nrows, 
                       report_dir)
  
}



# Level 2 internal functions ---------------------------------------------------


process_level_cluster <- function(top_table, 
                                  p_value, 
                                  cluster_size, 
                                  level, 
                                  meta, 
                                  condition) {
  if (is.na(p_value)) {
    p_value <- p_values[1]  
  }
  
  result <- get_curve_values(top_table, 
                             p_value, 
                             level, 
                             meta, 
                             condition)
  
  normalized_curves <- normalize_curves(result$curve_values)
  
  clustering_result <- hierarchical_clustering(normalized_curves, 
                                               cluster_size, 
                                               result$smooth_timepoints, 
                                               top_table)
}


#' @importFrom dplyr arrange mutate group_by summarize
#' @importFrom tidyr pivot_longer separate
#' @importFrom ComplexHeatmap Heatmap draw
#' @importFrom ggplot2 ggplot geom_line facet_wrap geom_vline ylab theme
#' @importFrom ggplot2 theme_bw scale_x_continuous
#' 
plot_heatmap <- function(data,
                         meta,
                         condition,
                         feature_names,
                         clustered_hits) {
  clusters <- clustered_hits %>% dplyr::arrange(cluster)
  data <- data[as.numeric(clusters$feature),]
  
  unique_elements <- unique(meta[[condition]])
  
  # Step 2 & 3: Get indices and subset the dataframe, then store results in a 
  # list
  metas_levels <- lapply(unique_elements, function(element) {
    # Get indices where the column matches the element
    indices <- which(meta[[condition]] == element)
    
    # Subset the dataframe using these indices
    meta[indices, ]
  })
  
  datas_levels <- lapply(unique_elements, function(element) {
    # Get indices where the column matches the element
    indices <- which(meta[[condition]] == element)
    
    # Subset the dataframe using these indices
    data[, indices]
  })
  
  
  BASE_TEXT_SIZE_PT <- 5
  
  ht_opt(
    simple_anno_size = unit(1.5, "mm"),
    COLUMN_ANNO_PADDING = unit(1, "pt"),
    DENDROGRAM_PADDING = unit(1, "pt"),
    HEATMAP_LEGEND_PADDING = unit(1, "mm"),
    ROW_ANNO_PADDING = unit(1, "pt"),
    TITLE_PADDING = unit(2, "mm"),
    heatmap_row_title_gp = gpar(fontsize = BASE_TEXT_SIZE_PT),
    heatmap_row_names_gp = gpar(fontsize = BASE_TEXT_SIZE_PT),
    heatmap_column_title_gp = gpar(fontsize = BASE_TEXT_SIZE_PT),
    heatmap_column_names_gp = gpar(fontsize = BASE_TEXT_SIZE_PT),
    legend_labels_gp = gpar(fontsize = BASE_TEXT_SIZE_PT),
    legend_title_gp = gpar(fontsize = BASE_TEXT_SIZE_PT),
    legend_border = FALSE
  )
  
  for (i in seq_along(datas_levels)) {
    data <- datas_levels[[i]]
    meta <- metas_levels[[i]]
    z_score <- t(scale(t(data)))
    
    ht <- ComplexHeatmap::Heatmap(z_score,
                         column_split = meta$Time,
                         cluster_columns = FALSE,
                         row_split = clusters$cluster,
                         cluster_rows = FALSE,
                         heatmap_legend_param = list(title = "z-score of 
                                                    log2 intensity",
                                                    title_position = 
                                                      "lefttop-rot"),
                  # row_gap = unit(2, "pt"),
                  # column_gap = unit(2, "pt"),
                  # width = unit(2, "mm") * ncol(z_score) + 5 * unit(2, "pt"), 
                  # height = unit(2, "mm") * nrow(z_score) + 5 * unit(2, "pt"), 
                  show_row_names = TRUE)
    
    print(ht)
    
    data_to_plot <- data.frame(first_protein_description = 
                                 rownames(data.matrix.batch.filt.sig), 
                               data.matrix.batch.filt.sig) %>%
      dplyr::mutate(cluster_number = clusters_exp$cluster) %>%
      tidyr::pivot_longer(cols = colnames(data.matrix.batch.filt.sig),
                   names_to = "sample_name",
                   values_to = "log2_intensity") %>%
      tidyr::separate(sample_name, 
               into = c("reactor", "time_point", "phase_of_fermentation"),
               sep = "_") %>%
      dplyr::mutate(time_to_feed = rep(meta_exp_filt$time_to_feed,
                                length(clusters_exp$feature))) %>%
      dplyr::group_by(first_protein_description) %>%
      dplyr::mutate(log2_intensity = rescale(log2_intensity))
    
    
    data_to_plot_mean_protein  <- data_to_plot %>%
      dplyr::group_by(first_protein_description, time_to_feed) %>%
      dplyr::mutate(mean_intensity_protein = mean(log2_intensity)) %>%
      ungroup()
    
    data_to_plot_mean_tp <- data_to_plot %>%
      dplyr::group_by(cluster_number, time_to_feed) %>%
      dplyr::summarise(mean_intensity_tp = mean(log2_intensity)) 
    
    clusters_exp %>%
      count(cluster)
    
    ggplot2::ggplot(data = data_to_plot_mean_protein) +
      geom_line(aes(x = time_to_feed, y = mean_intensity_protein, 
                    color = first_protein_description), alpha = 0.5) +
      geom_line(data = data_to_plot_mean_tp,aes(x = time_to_feed, 
                                                y = mean_intensity_tp), 
                linewidth = 0.8) +
      facet_wrap(~cluster_number, ncol = 2, 
                 labeller = labeller(cluster_number =  
                                       c("1" = "Cluster 1: 32 proteins",
                                         "2" = "Cluster 2: 48 proteins",
                                         "3" = "Cluster 3: 68 proteins",
                                         "4" = "Cluster 4: 29 proteins",
                                         "5" = "Cluster 5: 17 proteins",
                                         "6" = "Cluster 6: 13 proteins")))  +
      geom_vline(xintercept = 0, linetype = 'dashed', color = 'red', 
                 linewidth = 0.5) +  
      ylab("normalized log2 intensity") +
      theme_bw() +
      theme(legend.position = "none",
            panel.grid.minor = element_blank()) +
      scale_x_continuous(breaks = data_to_plot$time_to_feed)
    
    
    ht= ComplexHeatmap::draw(ht, heatmap_legend_side = "right")
    
    print(ht)
  }
  return(ht)
}


#' @importFrom stats as.dendrogram
#' @importFrom stats cutree
#' @importFrom RColorBrewer brewer.pal.info
#' @importFrom RColorBrewer brewer.pal
#' @importFrom dendextend color_branches
#' @importFrom dendextend as.ggdend
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 theme
#' 
plot_dendrogram <- function(hc, 
                            k, 
                            title) {
  dend <- stats::as.dendrogram(hc)
  clusters <- stats::cutree(hc, k)
  
  palette_name <- "Set3" 
  max_colors_in_palette <- 
    RColorBrewer::brewer.pal.info[palette_name, "maxcolors"]
  colors <- 
    RColorBrewer::brewer.pal(min(max_colors_in_palette, k), palette_name)
  if (k > max_colors_in_palette) {
    colors <- rep(colors, length.out = k)
  }
  
  dend_colored <- dendextend::color_branches(dend, k = k, 
                                             labels_colors = colors)
  dend_colored <- set(dend_colored, "labels", value = NULL)
  
  ggdend <- dendextend::as.ggdend(dend_colored)
  p_dend <- ggplot2::ggplot(ggdend) + 
    labs(title = title, 
         x = "", y = "") +
    theme_minimal() +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank())
}


#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 scale_color_brewer
#' @importFrom ggplot2 theme_minimal
#' 
plot_all_shapes <- function(curve_values, 
                            title) {
  time <- as.numeric(colnames(curve_values)[-length(colnames(curve_values))])
  
  clusters <- unique(curve_values$cluster)
  average_curves <- data.frame()
  
  # Loop through each unique cluster value to calculate the average curve
  for (current_cluster in clusters) {
    # Filter rows for the current cluster
    subset_hits <- curve_values[curve_values$cluster == current_cluster, ]
    last_timepoint <- (which(names(curve_values) == "cluster")) - 1
    average_curve <- colMeans(subset_hits[,1:last_timepoint])
    
    # Create a data frame for the average curve with an additional 'Cluster' 
    # column
    curve_df <- data.frame(Time = time, Value = average_curve, 
                           cluster = as.factor(current_cluster))
    
    # Bind the curve data frame to the cumulative data frame
    average_curves <- rbind(average_curves, curve_df)
  }
  
  average_curves$cluster <- 
    factor(average_curves$cluster, 
           levels = sort(unique(as.numeric(average_curves$cluster))))
  
  p_curves <- ggplot2::ggplot(average_curves, aes(x = Time, y = Value, color = 
                                           factor(cluster))) +
                              geom_line() + 
                              ggtitle(title) +
                              xlab("Timepoints") + ylab("Values") +
                              scale_color_brewer(palette = "Dark2", 
                                                 name = "Cluster") + 
                              theme_minimal()
}


#' Plot Single and Consensus Splines
#'
#' This function takes a time series data frame, transforms it, and plots both
#' individual time series and their consensus using ggplot2.
#'
#' @param time_series_data A data frame of time series data.
#' @param title The title of the plot.
#' @return A ggplot object representing the plot.
#' @importFrom dplyr arrange mutate
#' @importFrom tibble rownames_to_column
#' @importFrom tidyr pivot_longer
#' @importFrom ggplot2 ggplot geom_line scale_colour_manual theme_minimal
#' @importFrom ggplot2 ggtitle xlab ylab
#' 
plot_single_and_consensus_splines <- function(time_series_data, 
                                              title) {
  # Transform the dataframe to a long format for ggplot2
  df_long <- as.data.frame(t(time_series_data)) %>%
    tibble::rownames_to_column(var = "time") %>%
    tidyr::pivot_longer(cols = -time, names_to = "feature", 
                        values_to = "intensity") %>%
    dplyr::arrange(feature) %>%
    dplyr::mutate(time = as.numeric(time))
  
  # Compute consensus (mean of each column)
  consensus <- colMeans(time_series_data, na.rm = TRUE)
  consensus_df <- data.frame(time = as.numeric(colnames(time_series_data)), 
                             consensus = consensus)
  
  p <- ggplot2::ggplot() +
    geom_line(data = df_long, aes(x = time, y = intensity, group = feature,
                                  colour = "Single Shapes"),
              alpha = 0.3, linewidth = 0.5) +
    geom_line(data = consensus_df, aes(x = time, y = consensus,
                                       colour = "Consensus Shape"),
              linewidth = 1.5) +
    scale_colour_manual("", values = c("Consensus Shape" = "darkblue",
                                       "Single Shapes" = "#6495ED")) +
    theme_minimal() +
    ggtitle(title) +
    xlab("time to feeding [min]") +
    ylab("Y")
  
  return(p)
}


#' Plot Consensus Shapes for Each Cluster
#'
#' This function takes a dataframe containing curve values and their associated 
#' clusters,
#' and generates a plot for each cluster using the 
#' plot_single_and_consensus_splines function.
#' Each plot represents both the individual curves and their consensus within 
#' the cluster.
#'
#' @param curve_values A dataframe containing the curve values and a cluster 
#' identifier.
#'                     The last column is assumed to be the cluster column.
#' @param title The base title for the plots, which will be modified by 
#' appending the cluster number.
#' @return A list of ggplot objects, each representing a plot for a cluster.
#' 
plot_consensus_shapes <- function(curve_values, 
                                  title) {
  clusters <- sort(unique(curve_values$cluster))
  time <- as.numeric(colnames(curve_values)[-length(colnames(curve_values))])
  
  plots <- list()
  for (current_cluster in clusters) {
    current_title <- paste(title, current_cluster, sep = "_")
    subset_df <- subset(curve_values, cluster == current_cluster)
    subset_df$cluster <- NULL 
    
    plots[[length(plots) + 1]] <- plot_single_and_consensus_splines(
      subset_df, current_title)
  }
  return(plots)
}


#' Plot Splines for Features Based on Top Table Information
#'
#' This function generates plots for each feature listed in the top table using 
#' spline 
#' interpolation for fitted values. It creates individual plots for each feature 
#' and combines 
#' them into a single composite plot. The function is internal and not exported.
#'
#' @param top_table A dataframe containing the indices and names of features, 
#' along with their 
#'                  statistical metrics such as intercepts and spline 
#'                  coefficients.
#' @param data A matrix or dataframe containing the raw data values for each 
#' feature.
#' @param meta A dataframe containing metadata for the data, including time 
#' points.
#' @param main_title The main title to be used for the composite plot of all 
#' features.
#' @return A list containing the composite plot and the number of rows used in 
#' the plot layout.
#' @importFrom splines ns
#' @importFrom ggplot2 ggplot geom_point geom_line theme_minimal labs theme
#' @importFrom ggplot2 scale_x_continuous annotate
#' @importFrom patchwork wrap_plots plot_annotation
#' 
plot_splines <- function(top_table, 
                         data, 
                         meta, 
                         main_title) {
  
  DoF <- which(names(top_table) == "AveExpr") - 1
  time_points <- meta$Time
  
  titles <- data.frame(
    FeatureID = top_table$feature_index,
    feature_names = top_table$feature_names
  )
  
  plot_list <- list()
  
  ## Generate individual plots ----
  for (hit in 1:nrow(top_table)) {
    hit_index <- as.numeric(top_table$feature_index[hit])
    y_values <- data[hit_index, ]
    
    intercept <- top_table$intercept[hit]
    
    spline_coeffs <- as.numeric(top_table[hit, 1:DoF])
    
    Time <- seq(meta$Time[1], meta$Time[length(meta$Time)], length.out = 100)
    X <- splines::ns(Time, df = DoF, intercept = FALSE)
    
    fitted_values <- X %*% spline_coeffs + intercept
    
    plot_data <- data.frame(Time = time_points, Y = y_values)
    
    plot_spline <- data.frame(Time = Time, Fitted = fitted_values)
    
    x_max <- as.numeric(max(time_points))
    x_extension <- x_max * 0.05 
    
    p <- ggplot2::ggplot() +
      geom_point(data = plot_data, aes(x = Time, y = Y), color = 'blue') +
      geom_line(data = plot_spline, aes(x = Time, y = Fitted), 
                color = 'red') +
      theme_minimal() +
      scale_x_continuous(limits = c(min(time_points), x_max + x_extension)) +
      labs(x = "Time [min]", y = "Intensity")
    
    matched_row <- subset(titles, FeatureID == hit_index)
    title <- as.character(matched_row$feature_name)
    if (is.na(title)) {
      title <- paste("feature:", hit_index)
    }
    
    p <- p + labs(title = title, 
                  x = "Time [min]", y = "Intensity") +
      theme(plot.title = element_text(size = 4),
            axis.title.x = element_text(size = 8), 
            axis.title.y = element_text(size = 8)) +
      annotate("text", x = x_max + (x_extension / 2), y = 
                 max(fitted_values, na.rm = TRUE),
               label = "",
               hjust = 0.5, vjust = 1, size = 3.5, angle = 0, color = "black")
    
    plot_list[[length(plot_list) + 1]] <- p
  }
  
  ## Generate the combined plot ----
  if(length(plot_list) > 0) {           
    num_plots <- length(plot_list)
    ncol <- 3
    nrows <- ceiling(num_plots / ncol)
    
    composite_plot <- patchwork::wrap_plots(plot_list, ncol = 3) + 
      patchwork::plot_annotation(title = paste(main_title, "| DoF:", DoF),
                      theme = theme(plot.title = element_text(hjust = 0.5, 
                                                              size = 14)))
    return(list(composite_plot = composite_plot, nrows = nrows))
  } else {
    stop("plot_list in function plot_splines splinetime package has length 0!")
  }
}


#' Generate HTML Report with Plot List
#'
#' This function generates an HTML report for a given list of plots. It 
#' includes
#' headers and design details specific to the data type being analyzed, and 
#' saves
#' the report in the specified directory. The function is internal and not 
#' exported.
#'
#' @param plot_list A list of ggplot objects to be included in the report.
#' @param plot_list_nrows The number of rows to arrange the plots in the report.
#' @param report_dir The directory where the report HTML file will be saved.
#' @importFrom here here
#' @importFrom tools file_path_sans_ext
#' @importFrom grDevices dev.off
#' @importFrom htmltools save_html
#' 
generate_report_html <- function(plot_list, 
                                 plot_list_nrows, 
                                 report_dir) {
  timestamp <- format(Sys.time(), "%d_%m_%Y-%H_%M_%S")
  
  omics_data_type <- "PTX"
  header_text <- paste("limma clustered hits", 
                       omics_data_type, timestamp, sep=" | ")
  
  if (omics_data_type == "PTX") {
    design_text <- "splines | X,data = exp AND stat | limma design: 1 + 
      Phase*X + Reactor | timepoints: E12_TP05_Exponential & 
      E10_TP10_Stationary removed<br>(Note: batch-corrected data used for 
      plotting
      individual blue datapoints (plots with the red spline, below))"
  } else if (omics_data_type == "PPTX") {
    design_text <- "splines | X,data = exp AND stat | limma design: 1 + 
      Phase*X + Reactor | timepoints: all<br>(Note: batch-corrected data used 
      for plotting
      individual blue datapoints (plots with the red spline, below))"
  }
  
  html_content <- paste(
    "<html><head><title>My Plots</title></head><body>",
    "<h1 style='color:red;'>", header_text, "</h1>",
    "<h2>Design</h2>",
    "<p>", design_text, "</p>",
    "</body></html>",
    sep=""
  )
  
  file_name <- sprintf("report_clustered_splines_%s_%s.html",
                       omics_data_type, timestamp)
  
  output_file_path <- here::here(report_dir, file_name)
  
  build_plot_report_html(html_content, 
                         plot_list, 
                         plot_list_nrows, 
                         output_file_path)
}


# Level 3 internal functions ---------------------------------------------------


#' Calculate Curve Values Based on Top Table Filter
#'
#' This function filters entries from a given top table based on an adjusted 
#' p-value threshold,
#' performs spline interpolation using specified degrees of freedom, and 
#' calculates curve values 
#' for the selected entries at predefined time points. The function is 
#' internal and not exported.
#'
#' @param top_table A data frame containing data with a column for adjusted 
#' p-values and 
#'                  expression averages which indicate the number of degrees 
#'                  of freedom.
#' @param p_value The threshold for filtering entries based on adjusted
#' p-values.
#' @param level The specific level of the condition to filter on in the 
#' metadata.
#' @param meta Metadata containing time points and conditions.
#' @param condition The name of the condition column in the metadata to filter 
#' on.
#' @return A list containing two elements: `curve_values`, a data frame of 
#' curve values for each filtered entry, and `smooth_timepoints`, the time
#' points at which curves were evaluated.
#' 
#' @importFrom dplyr select all_of
#' @importFrom splines ns
#' 
get_curve_values <- function(top_table, 
                             p_value, 
                             level, 
                             meta, 
                             condition) {
  spline_results_hits <- subset(top_table, adj.P.Val < p_value)
  
  subset_meta <- meta[meta[[condition]] == level, ]
  
  smooth_timepoints <- seq(subset_meta$Time[1],
                           subset_meta$Time[length(subset_meta$Time)],
                           length.out = 100)
  
  
  args <- list(x = smooth_timepoints, intercept = FALSE)
  
  if (!is.null(spline_params$DoFs)) {
    args$df <- spline_params$DoFs[1]
  } else {
    args$knots <- spline_params$knots[[1]]
  }
  
  if (!is.null(spline_params$bknots)) {
    args$Boundary.knots <- spline_params$bknots[[1]]
  }
  
  
  if (spline_params$spline_type[1] == "b") {
    args$degree <- spline_params$degrees[1]
    X <- do.call(splines::bs, args)
  } else {                                          # natural cubic splines
    X <- do.call(splines::ns, args)
  }
  
  DoF <- which(names(top_table) == "AveExpr") - 1

  columns_to_select <- 1:DoF
  
  splineCoeffs <- spline_results_hits %>%
    dplyr::select(all_of(1:DoF)) %>%
    as.matrix()
  
  curve_values <- matrix(nrow = nrow(splineCoeffs),
                         ncol = length(smooth_timepoints))
  
  for(i in 1:nrow(splineCoeffs)) {
    current_coeffs <- matrix(splineCoeffs[i, ], ncol = ncol(splineCoeffs),
                             byrow = TRUE)
    
    curve_values[i, ] <- current_coeffs %*% t(X)
  }
  
  curve_values <- as.data.frame(curve_values)
  rownames(curve_values) <- rownames(splineCoeffs)
  list(curve_values = curve_values, smooth_timepoints = smooth_timepoints)
}


#' Normalize Curve Values
#'
#' This function normalizes each row in a data frame or matrix of curve values. 
#' Normalization is performed so that each row's values range from 0 
#' (corresponding to the 
#' minimum value of the row) to 1 
#' (corresponding to the maximum value of the row).
#'
#' @param curve_values A data frame or matrix of curve values where each row 
#' represents 
#'        a curve and each column a time point.
#' @return A data frame or matrix with the same dimensions as the input, where
#'  each row 
#'         has been normalized.
#' @examples
#' data <- matrix(runif(100), nrow=10)
#' normalized_data <- normalize_curves(data)
normalize_curves <- function(curve_values) {
  normalized_curves <- apply(curve_values, 1, function(row) {
    (row - min(row)) / (max(row) - min(row))
  })
  
  normalized_curves <- t(normalized_curves)
  curve_values[,] <- normalized_curves
  curve_values
}


#' Hierarchical Clustering of Curve Values
#'
#' Performs hierarchical clustering on given curve values. It can automatically 
#' determine the optimal number of clusters using silhouette analysis or use a 
#' specified number. The function adjusts the provided top_table with cluster 
#' assignments.
#'
#' @param curve_values A matrix or data frame of curve values to cluster.
#' @param k The number of clusters to use or "auto" to automatically determine 
#'          the optimal number using silhouette width analysis.
#' @param smooth_timepoints Numeric vector of time points corresponding to 
#'                          columns in curve_values.
#' @param top_table Data frame to be updated with cluster assignments.
#' @return A list containing clustering results and the modified top_table.
#' 
#' @importFrom stats dist hclust cutree
#' @importFrom cluster silhouette
#' 
hierarchical_clustering <- function(curve_values, 
                                    k, 
                                    smooth_timepoints,
                                    top_table) {
  distance_matrix <- stats::dist(curve_values, method = "euclidean")
  hc <- stats::hclust(distance_matrix, method = "complete")
  
  if (is.character(k) && k == "auto") {
    # Calculate silhouette width for a range of clusters
    max_clusters <- 8
    sil_widths <- numeric(max_clusters - 1)
    for (i in 2:max_clusters) {
      temp_clusters <- stats::cutree(hc, k = i)
      silhouette_score <- 
        mean(cluster::silhouette(temp_clusters, distance_matrix)[, "sil_width"])
      
      adjusted_score <- silhouette_score + (0.02 * log(i)) # scaling factor
      sil_widths[i - 1] <- adjusted_score
    }
    
    # Find the index of the maximum adjusted silhouette score
    best_k_index <- which.max(sil_widths)
    k <- best_k_index + 1  # because index shift due to starting at 2 clusters
    
    cluster_assignments <- stats::cutree(hc, k = k)
  } else if (is.numeric(k)) {
    cluster_assignments <- stats::cutree(hc, k = k)
  }

  clustered_hits <- data.frame(cluster = cluster_assignments)
  top_table_hits <- dplyr::filter(top_table, adj.P.Val < 0.05)
  clustered_hits$feature <- top_table_hits$feature_index
  clustered_hits <- clustered_hits[, c("feature", "cluster")]
  
  colnames(curve_values) <- smooth_timepoints
  curve_values$cluster <- cluster_assignments
  
  top_table$cluster <- NA
  top_table$cluster[1:nrow(clustered_hits)] <-
    as.integer(clustered_hits$cluster)
  
  group_clustering <- list(clustered_hits = clustered_hits,
                           hc = hc,
                           curve_values = curve_values,
                           top_table = top_table,
                           clusters = k)
}

